# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(590, 780)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, 0, 591, 780))
        self.stackedWidget.setObjectName("stackedWidget")
        self.select_workflow = QtWidgets.QWidget()
        self.select_workflow.setObjectName("select_workflow")
        self.Welcome = QtWidgets.QLabel(self.select_workflow)
        self.Welcome.setGeometry(QtCore.QRect(0, 0, 590, 780))
        self.Welcome.setText("")
        self.Welcome.setPixmap(QtGui.QPixmap(":/images/Picture1.png"))
        self.Welcome.setScaledContents(True)
        self.Welcome.setObjectName("Welcome")
        self.patient_id_edit = QtWidgets.QLineEdit(self.select_workflow)
        self.patient_id_edit.setGeometry(QtCore.QRect(230, 689, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.patient_id_edit.setFont(font)
        self.patient_id_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.patient_id_edit.setObjectName("patient_id_edit")
        self.go_to_execute_workflow_page = QtWidgets.QPushButton(self.select_workflow)
        self.go_to_execute_workflow_page.setGeometry(QtCore.QRect(450, 660, 111, 101))
        self.go_to_execute_workflow_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.go_to_execute_workflow_page.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.go_to_execute_workflow_page.setText("")
        self.go_to_execute_workflow_page.setObjectName("go_to_execute_workflow_page")
        self.stackedWidget.addWidget(self.select_workflow)
        self.workflow_status = QtWidgets.QWidget()
        self.workflow_status.setObjectName("workflow_status")
        self.label = QtWidgets.QLabel(self.workflow_status)
        self.label.setGeometry(QtCore.QRect(30, 10, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(51, 137, 187);")
        self.label.setObjectName("label")
        self.step_indicator_text = QtWidgets.QLabel(self.workflow_status)
        self.step_indicator_text.setGeometry(QtCore.QRect(160, 10, 31, 81))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.step_indicator_text.setFont(font)
        self.step_indicator_text.setStyleSheet("color: rgb(51, 137, 187);")
        self.step_indicator_text.setObjectName("step_indicator_text")
        self.divider_text = QtWidgets.QLabel(self.workflow_status)
        self.divider_text.setGeometry(QtCore.QRect(190, 10, 31, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.divider_text.setFont(font)
        self.divider_text.setStyleSheet("color: rgb(51, 137, 187);")
        self.divider_text.setObjectName("divider_text")
        self.total_steps_text = QtWidgets.QLabel(self.workflow_status)
        self.total_steps_text.setGeometry(QtCore.QRect(220, 10, 31, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.total_steps_text.setFont(font)
        self.total_steps_text.setStyleSheet("color: rgb(51, 137, 187);")
        self.total_steps_text.setObjectName("total_steps_text")
        self.information_text = QtWidgets.QLabel(self.workflow_status)
        self.information_text.setGeometry(QtCore.QRect(30, 80, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(21)
        font.setBold(False)
        font.setWeight(50)
        self.information_text.setFont(font)
        self.information_text.setStyleSheet("color: rgb(51, 137, 187);")
        self.information_text.setObjectName("information_text")
        self.line = QtWidgets.QFrame(self.workflow_status)
        self.line.setGeometry(QtCore.QRect(30, 130, 531, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.line.setPalette(palette)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.guide_image_display = QtWidgets.QLabel(self.workflow_status)
        self.guide_image_display.setGeometry(QtCore.QRect(30, 160, 531, 361))
        self.guide_image_display.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.guide_image_display.setText("")
        self.guide_image_display.setScaledContents(True)
        self.guide_image_display.setObjectName("guide_image_display")
        self.information_text_2 = QtWidgets.QLabel(self.workflow_status)
        self.information_text_2.setGeometry(QtCore.QRect(30, 510, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.information_text_2.setFont(font)
        self.information_text_2.setStyleSheet("color: rgb(51, 137, 187);")
        self.information_text_2.setObjectName("information_text_2")
        self.step_description = QtWidgets.QLabel(self.workflow_status)
        self.step_description.setGeometry(QtCore.QRect(30, 560, 531, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(89, 129, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 129, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 129, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 129, 150, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 129, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 129, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 129, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 129, 150, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 129, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 129, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 129, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 129, 150, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.step_description.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.step_description.setFont(font)
        self.step_description.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.step_description.setAutoFillBackground(False)
        self.step_description.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"color: rgb(89, 129, 150);")
        self.step_description.setLineWidth(1)
        self.step_description.setText("")
        self.step_description.setTextFormat(QtCore.Qt.RichText)
        self.step_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.step_description.setWordWrap(True)
        self.step_description.setObjectName("step_description")
        self.go_to_next_step = QtWidgets.QPushButton(self.workflow_status)
        self.go_to_next_step.setGeometry(QtCore.QRect(480, 690, 80, 80))
        self.go_to_next_step.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.go_to_next_step.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.go_to_next_step.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ic_arrow-right.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.go_to_next_step.setIcon(icon)
        self.go_to_next_step.setIconSize(QtCore.QSize(80, 80))
        self.go_to_next_step.setObjectName("go_to_next_step")
        self.go_to_previous_step = QtWidgets.QPushButton(self.workflow_status)
        self.go_to_previous_step.setGeometry(QtCore.QRect(30, 690, 80, 80))
        self.go_to_previous_step.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.go_to_previous_step.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.go_to_previous_step.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/ic_arrow-left.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.go_to_previous_step.setIcon(icon1)
        self.go_to_previous_step.setIconSize(QtCore.QSize(80, 80))
        self.go_to_previous_step.setObjectName("go_to_previous_step")
        self.step_check_lable = QtWidgets.QLabel(self.workflow_status)
        self.step_check_lable.setGeometry(QtCore.QRect(460, 20, 100, 100))
        self.step_check_lable.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.step_check_lable.setText("")
        self.step_check_lable.setPixmap(QtGui.QPixmap(":/images/ic_not_done.gif"))
        self.step_check_lable.setScaledContents(True)
        self.step_check_lable.setObjectName("step_check_lable")
        self.stackedWidget.addWidget(self.workflow_status)
        self.Crash_page = QtWidgets.QWidget()
        self.Crash_page.setObjectName("Crash_page")
        self.label_2 = QtWidgets.QLabel(self.Crash_page)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(51, 137, 187);")
        self.label_2.setObjectName("label_2")
        self.information_text_3 = QtWidgets.QLabel(self.Crash_page)
        self.information_text_3.setGeometry(QtCore.QRect(30, 80, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(21)
        font.setBold(False)
        font.setWeight(50)
        self.information_text_3.setFont(font)
        self.information_text_3.setStyleSheet("color: rgb(51, 137, 187);")
        self.information_text_3.setObjectName("information_text_3")
        self.line_2 = QtWidgets.QFrame(self.Crash_page)
        self.line_2.setGeometry(QtCore.QRect(30, 130, 531, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.line_2.setPalette(palette)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.step_check_lable_2 = QtWidgets.QLabel(self.Crash_page)
        self.step_check_lable_2.setGeometry(QtCore.QRect(460, 20, 100, 100))
        self.step_check_lable_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.step_check_lable_2.setText("")
        self.step_check_lable_2.setPixmap(QtGui.QPixmap(":/images/ic_not_done.gif"))
        self.step_check_lable_2.setScaledContents(True)
        self.step_check_lable_2.setObjectName("step_check_lable_2")
        self.crash_image_display = QtWidgets.QLabel(self.Crash_page)
        self.crash_image_display.setGeometry(QtCore.QRect(30, 160, 531, 341))
        self.crash_image_display.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.crash_image_display.setText("")
        self.crash_image_display.setScaledContents(True)
        self.crash_image_display.setObjectName("crash_image_display")
        self.information_text_4 = QtWidgets.QLabel(self.Crash_page)
        self.information_text_4.setGeometry(QtCore.QRect(30, 500, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.information_text_4.setFont(font)
        self.information_text_4.setStyleSheet("color: rgb(51, 137, 187);")
        self.information_text_4.setObjectName("information_text_4")
        self.Error_information = QtWidgets.QLabel(self.Crash_page)
        self.Error_information.setGeometry(QtCore.QRect(30, 550, 531, 151))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(32, 88, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 88, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Error_information.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.Error_information.setFont(font)
        self.Error_information.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Error_information.setAutoFillBackground(False)
        self.Error_information.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.Error_information.setLineWidth(1)
        self.Error_information.setText("")
        self.Error_information.setTextFormat(QtCore.Qt.RichText)
        self.Error_information.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Error_information.setWordWrap(True)
        self.Error_information.setObjectName("Error_information")
        self.exit = QtWidgets.QPushButton(self.Crash_page)
        self.exit.setGeometry(QtCore.QRect(460, 720, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 137, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 137, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 137, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 137, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 137, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 137, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 137, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 137, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 137, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.exit.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 137, 187);")
        self.exit.setObjectName("exit")
        self.stackedWidget.addWidget(self.Crash_page)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Titanium Scaffold Workflow"))
        self.label.setText(_translate("Form", "Step"))
        self.step_indicator_text.setText(_translate("Form", "1"))
        self.divider_text.setText(_translate("Form", "/"))
        self.total_steps_text.setText(_translate("Form", "1"))
        self.information_text.setText(_translate("Form", "Current Step"))
        self.information_text_2.setText(_translate("Form", "Description"))
        self.label_2.setText(_translate("Form", "Orz"))
        self.information_text_3.setText(_translate("Form", "Shit things happen."))
        self.information_text_4.setText(_translate("Form", "Error Info"))
        self.exit.setText(_translate("Form", "Exit"))
import main_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
